name: Mathics3 (macOS)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build:
    env:
      LDFLAGS: "-L/usr/local/opt/llvm@14/lib"
      CPPFLAGS: "-I/usr/local/opt/llvm@14/include"
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: ['3.10', '3.11']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install OS dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install stopit
      run: |
        pip install "setuptools>=70.0.0" packaging pytest
        pip install -e .
    - name: Test Stopit
      run: |
        python tests.py
